### ISSUE TITLE
Atharva Patil To-do list

### ISSUE THREAD

**Issue by hrushipandit** [obi-wan-shinobi/BE-Project-Documentation#18]
Stage 1 Report- To Do List

Section 4: 4.1 Introduction, 4.2 Usage Scenario
Section 5 Detailed Design Document 5.1 Introduction ,5.2 Architectural Design ,5.3 Data Design,

**Comment by Atharva1701** [comment]
Added the Use Cases

**Comment by hrushipandit** [comment]
> Added the Use Cases

Good work
