### ISSUE TITLE
Shreyas Kalvankar To-do list

### ISSUE THREAD

**Issue by hrushipandit** [obi-wan-shinobi/BE-Project-Documentation#20]
Stage 1 Report- To Do List

Section 2 Problems Definition and scope: 2.2 : Major Constraints, 2.3 : Methodologies of Problem Solving and Efficiency issues 2.4 : Scenario in which multi-core,Embedded and Distributed Computing is used, 2.5: Outcomes
Section 4 Software Requirement Specification: 4.2 Usage Scenario, 4.3 Data Model and Description
Section 6 Dataset and Experimental Setup

**Comment by obi-wan-shinobi** [comment]
Started working on this 👍🏻
